# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/main/avatars/'),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
