# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180319_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Class'),
        ),
    ]
